FROM php:8.4-fpm

WORKDIR /var/www

RUN apt-get update && apt-get install -y \
    git \
    curl \
    unzip \
    zip \
    libicu-dev \
    libzip-dev

RUN docker-php-ext-install \
    pdo_mysql \
    intl \
    zip \
    bcmath

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

CMD ["php-fpm"]
