services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.dev
    environment:
      APP_ENV: local
      APP_DEBUG: true
    volumes:
      - ./:/var/www

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: laravel_node
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www
    networks:
      - app-network
