services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      APP_ENV: production
      APP_DEBUG: false

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: laravel_node_prod
    restart: unless-stopped
    working_dir: /var/www
    networks:
      - app-network
